### ISSUE TITLE
Switching from one WizardScene to another causes infinite loop.

### ISSUE THREAD

**Issue by brookmg** [telegraf/telegraf#1241]
## Context

If one tries to switch to another wizard from `wizard.leave( ctx => { ... } )`, it will cause an infinite loop that causes `RangeError: Maximum call stack size exceeded`. 

* Telegraf.js Version: 3.36.0
* Node.js Version: v14.15.1
* Operating System: Windows 10 x64 20H2

## Expected Behavior

The `ctx.scene.enter( sceneId )` function shouldn't assume the action of the user and call `ctx.scene.leave()`. Atleast there should be an option to block this trigger to avoid infinite loop.

## Current Behavior

If one tries to switch to another wizard from `wizard.leave( ctx => { ... } )`, it will cause an infinite loop that causes `RangeError: Maximum call stack size exceeded`. 

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Enter a specific WizardScene
2. Simulate moving to another WizardScene when the user leaves the current one ( using the `leave` callback method )
3. This should crash the module

### Failure Logs

RangeError: Maximum call stack size exceeded

**Comment by KnorpelSenf** [comment]
Could you retry from source (`npm i telegraf/telegraf`) or at least with the most recent version 3.38.0? I'm not familiar with the code base from back then, and there have been a lot of changes already. It is possible that your problem is already solved.

**Comment by brookmg** [comment]
Sure I will do that. But I feel like this was a design problem. Give me a sec

**Comment by brookmg** [comment]
https://github.com/brookmg/TelegrafBotSample Check out this sample repo and see the instruction I placed on index.js. The problem is still present on 3.38.0 but like I said it's more of a design decision than a bug. Just wish if there was a way to disable the default operation

**Comment by KnorpelSenf** [comment]
I see, thank you! That helped a lot.

Did you try passing `silent = true` to the call in [this line](https://github.com/brookmg/TelegrafBotSample/blob/b82e914435436bcc9e8f369f4705b001b2d1fa24/index.js#L30)?

```ts
  ctx.scene.enter('scene_2', {}, true)
```

**Comment by brookmg** [comment]
I just did and it doesn't call the `Scene.enter` callback for the newly entered scene.

**Comment by KnorpelSenf** [comment]
Damn it, I missed that, you're right. Then I see now way around, this needs to be fixed (preferably automatically and without requiring settings the correct flags).

Thanks for reporting this.

**Comment by KnorpelSenf** [comment]
If we want to support what you're trying to do, then this raises a question.

Let's assume there are three scenes called X, Y, and Z.

1. User is in X
2. X has leaveHandler that calls `enter(Y)`
3. User requests to go to Z

As Z shall be entered, X will be left. The `leaveHandler` of X want to switch over to Y, but in fact we are in the middle of switching over to Z. What do you expect to happen now?

**Comment by brookmg** [comment]
Yes, I see your point. But the destination scene the user should be redirected to is actually passed through the context for the `leaveHandler`. We wanted to place all navigation in one place to make it clearly visible and easily switchable. [this](https://github.com/brookmg/TelegrafBotSample/blob/b82e914435436bcc9e8f369f4705b001b2d1fa24/index.js#L30) is an example but it would be a switch for a bigger bot

**Comment by brookmg** [comment]
Interestingly [this](https://github.com/telegraf/telegraf/blob/a221c8b99db3fd005c447a9728068e15962a7cb2/src/scenes/context.ts#L92) should've been the answer. Silent does what I needed but it's not calling the enter callback for the new scene.

**Comment by KnorpelSenf** [comment]
Hm. So what are you suggesting?

What exactly are you even trying to achieve by calling `enter` during `leave`?

**Comment by brookmg** [comment]
Pass to a different scene. I suggest defining the extent of the silent flag. Do I want to silence the `leaveHandler` and `enterHandler` or just one of them.

**Comment by wojpawlik** [comment]
Disclaimer: I'm unfamiliar with scenes.

`wizard.leave(ctx => ctx.scene.enter("X"))` makes it impossible to leave the `wizard`!

Why not `ctx.scene.enter("X")` directly? And adjust typings to make it impossible to access `ctx.scene.enter` from within `wizard.leave`.

**Comment by brookmg** [comment]
@wojpawlik  I don't think the framework should make that kind of decision for the developers. It's better to make the methods pure with no side effect ( leaving the current scene being the side effect here ).

**Comment by wojpawlik** [comment]
Then it'd have to be possible to be in multiple scenes at once, what would that even mean?

**Comment by brookmg** [comment]
There is already a `silent` flag that does what I'm asking. `ctx.scene.enter` would be called from `wizard.leave`.

**Comment by wojpawlik** [comment]
Perhaps `silent` flag should be dropped in 4.0.0 then? It allows to easily break expectations.

**Comment by brookmg** [comment]
I explained the use case above. https://github.com/telegraf/telegraf/issues/1241#issuecomment-747102474 If you think this is not worth considering then I can simply fork and use that for the time being.

**Comment by KnorpelSenf** [comment]
> Maybe I should open a PR to demonstrate what I'm saying.

I would love that! This is a relevant problem, and we should not let this discussion prevent us from finding a good solution.

I have to admit that I wouldn't really know what to do about it, i.e. which design would be better. Not automatically leaving the previous scene when entering a new one does not feel right.

**Comment by brookmg** [comment]
@KnorpelSenf  Sure I agree and you shouldn't place the burden of maintaining the state on the developer. I'm simply asking for a way to be able to handle that manually.

**Comment by KnorpelSenf** [comment]
I do see this need, I just wouldn't really know how to go about it. Introduce a fourth parameter, so we'd end up with `silentLeave` and `silentEnter`? Scenes and Wizards are already difficult to understand, that's why I'm so hesitant towards adding more configuration in order to prevent infinite recursion. I'd like to have something that—by design—just does not crash, but I cannot come up with something. I'm open for suggestions (explicitly including PRs).

**Comment by brookmg** [comment]
Yap, I was thinking about a 4th parameter too. I'm moving on from this then. Maybe add a warning or something on the documentation to show people not to use this method inside `Wizard.leave`. There is like a single example around wizards and stage. Thank you @KnorpelSenf and @wojpawlik for the discussion 👍

**Comment by wojpawlik** [comment]
How about adding `private leaving = false` property to `SceneContextScene`, set it to `true` while `SceneContextScene::leave` is running, and don't call `SceneContextScene::leave` again if it's set?

**Comment by brookmg** [comment]
I think that could work. The silent flag wouldn't have to be set either so no missed communication about it's functionality
